export const ACCORDIONTITLE1 = "When does the workshop start and what are the timings? "
export const ACCORDIONTITLE2 = "Will this be live or pre-recorded? "
export const ACCORDIONTITLE3 = "I made the payment but didn't receive any confirmation email.? "
export const ACCORDIONTITLE4 = "Since the workshop is live, will you be sharing recordings? "
export const ACCORDIONTITLE5 = "Can I get a refund?  "
export const ACCORDIONTITLE6 = "When can I receive the bonuses? "
export const ACCORDIONTITLE7 = "Will I get a certificate after completion? "
export const ACCORDIONTITLE8 = "Do you have an affiliate program? "

export const CONTENT1 = "You can get all the details related to the timings and dates of the workshop at the top of the page. "
export const CONTENT2 = "It’s going to be a completely live session. "
export const CONTENT3 = "Write to hi@growthschool.io and our awesome support team will solve your queries in the fastest time possible. "
export const CONTENT4 = "No, we won’t be sharing any recordings. Since it’s a live workshop, it’s expected that each participant will attend the workshop live. Also, recordings of a live session are just boring. "
export const CONTENT5 = "No. We don’t provide refunds in any case. If you are not sure about the workshop, check out the testimonials, read more about the trainer and take an informed decision. In case you miss out on attending the live workshop, we can move you to the next batch only ONCE. "
export const CONTENT6 = "After the workshop is done, you will receive all the bonuses within 48 hours. "
export const CONTENT7 = "Yes, you will receive a certificate of completion if you finish the entire workshop."
export const CONTENT8 = "Yes, you will receive a certificate of completion if you finish the entire workshop."